In [1]:
import numpy as np

In [2]:
# Create activation Function (Sigmoid)
def sigmoid(x):
  return 1 / (1 +np.exp(-x))

In [4]:
training_inputs = np.array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
print(training_inputs) 

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [6]:
training_outputs = np.array([[0],[1],[1],[0]])
print(training_outputs)

[[0]
 [1]
 [1]
 [0]]


In [13]:
# initialize weights for every inputs
# random values
np.random.seed(1)
weights = 2 * np.random.random((3,1)) - 1 
weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [14]:
# we pass input to activation function
for i in range(1):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer , weights)) 

In [15]:
outputs

array([[0.2689864 ],
       [0.3262757 ],
       [0.23762817],
       [0.36375058]])

In [19]:
outputs.round() # wrong output
# now we have to train model by gradient descent

array([[0.],
       [0.],
       [0.],
       [0.]])

In [20]:
def sigmoid_derivative(x):
  return x*(1-x)

In [23]:
for i in range(1000):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer , weights)) 
  error = training_outputs - outputs # to find errors
  adjustments = error * sigmoid_derivative(outputs) # how much change we have to do
  weights += np.dot(input_layer.T, adjustments) # we have different shapes of both so we have to transpose


In [24]:
weights

array([[ 7.26390912],
       [-0.21614179],
       [-3.41757429]])

In [25]:
outputs

array([[0.03176745],
       [0.97416005],
       [0.97907779],
       [0.02575143]])

In [27]:
outputs.round() # Now we have correct output

array([[0.],
       [1.],
       [1.],
       [0.]])