In [1]:
import numpy as np

In [2]:
input_samples = np.array([[0,1,0], [1,0,1], [0,0,1], [1,1,0]])
output_samples = np.array([[0], [1], [0], [1]])

In [3]:
input_samples


array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [4]:
output_samples

array([[0],
       [1],
       [0],
       [1]])

In [5]:
weights = np.random.random((3,1))
weights

array([[0.91405019],
       [0.67208228],
       [0.82552935]])

In [6]:
sum = np.dot(input_samples, weights) + 0.02 ## 0.02 is bias
sum

array([[0.69208228],
       [1.75957954],
       [0.84552935],
       [1.60613247]])

In [7]:
# Create The Activateion Function   (SIGMOID)
def activation(x):
  return 1 / (1 + np.exp(-x)) # Formula of Sigmoid

In [8]:
ypred = activation(sum)
ypred

array([[0.66642998],
       [0.85315699],
       [0.69962848],
       [0.83287374]])

In [10]:
# So the Output Above is [1][1][1][1] but we expected [0][1][0][1]
# Now we have to train the data

sum = np.dot(input_samples, weights) + 0.02 ## 0.02 is bias
ypred = activation(sum)
error = output_samples - ypred # actual - predicted
error

array([[-0.66642998],
       [ 0.14684301],
       [-0.69962848],
       [ 0.16712626]])

In [11]:
def gradient(x):
  return x * (1-x) # Derivative of sigmoid

In [12]:
sum = np.dot(input_samples, weights) + 0.02 ## 0.02 is bias
ypred = activation(sum)
error = output_samples - ypred # actual - predicted
# Apply Gradient Descent
adjustment = error * gradient(ypred)  
# Apply Back Propagation
weights =  weights + np.dot(input_samples, adjustment)
error

ValueError: ignored

In [13]:
# Above error comes beacuse we r using different shapes
# so we take transpose to remove this error

input_samples.shape

(4, 3)

In [15]:
input_samples.T.shape

(3, 4)

In [16]:
sum = np.dot(input_samples, weights) + 0.02 ## 0.02 is bias
ypred = activation(sum)
error = output_samples - ypred # actual - predicted
# Apply Gradient Descent
adjustment = error * gradient(ypred)  
# Apply Back Propagation
weights =  weights + np.dot(input_samples.T, adjustment)
error

array([[-0.66642998],
       [ 0.14684301],
       [-0.69962848],
       [ 0.16712626]])

In [ ]:
# So, when when we run above cell,if it dont reduce the size near to zero ,and not display correct output
# then we take loop and run that cell according to correct output

for i in range(1):
  sum = np.dot(input_samples, weights) + 0.02 ## 0.02 is bias
  ypred = activation(sum)
  error = output_samples - ypred # actual - predicted
  # Apply Gradient Descent
  adjustment = error * gradient(ypred)  
  # Apply Back Propagation
  weights =  weights + np.dot(input_samples.T, adjustment)
error

In [23]:
weights

array([[ 7.13662129],
       [-3.40639957],
       [-3.40639952]])

In [24]:
ypred # Now, You can see that, output is correct [0][1][0][1]

array([[0.03273971],
       [0.97701612],
       [0.03273971],
       [0.97701612]])

In [25]:
ypred.round()


array([[0.],
       [1.],
       [0.],
       [1.]])

In [30]:
# NOW Recheck,that how we accurate train 

new_samples = np.array([[1,1,1], [0,0,0]])
sum = np.dot(new_samples, weights) + 0.02 ## 0.02 is bias
ypred = activation(sum)
ypred

array([[0.58511868],
       [0.50499983]])

In [31]:
ypred.round()

array([[1.],
       [1.]])

In [ ]:
# The above input sample is just an ideal data, but the main purpose is to tell how model willbe train
# And when this model will be trained, then it provide output according what it trained 